// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwolkcegoeqnewfqhtei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53b2xrY2Vnb2VxbmV3ZnFodGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDU3NzAsImV4cCI6MjA2NzA4MTc3MH0.-9DLf_WUIbxuT6OMBttL6YPGwMB-hfNjwZpYHvPt-Io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});